# Generated by Django 4.2.5 on 2023-09-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_description_item_deskripsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expired',
            field=models.CharField(default='Mon 11 September 2023', max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('ot', 'Penyakit Orang Tua'), ('An', 'Khusus Anak (0-17 tahun)'), ('g', 'Generic'), ('h', 'Herbal/Suplemen'), ('pd', 'Penyakit dalam'), ('a', 'Alergi'), ('r', 'Racik')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('b', 'Botol/Sirup'), ('k', 'Kotak/Kemasan'), ('s', '1 Strip'), ('c', '1 Butir Kapsul')], default='Kapsul', max_length=100),
        ),
    ]
