# Generated by Django 4.2.5 on 2023-09-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_expired_alter_item_jenis_obat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expired',
            field=models.CharField(default='Sun 17 September 2023', max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('a', 'Alergi'), ('ot', 'Penyakit Orang Tua'), ('h', 'Herbal/Suplemen'), ('g', 'Generic'), ('An', 'Khusus Anak (0-17 tahun)'), ('r', 'Racik'), ('pd', 'Penyakit dalam')], default='Generic', max_length=100),
        ),
    ]
