# Generated by Django 4.2.5 on 2023-09-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_item_expired_alter_item_jenis_obat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expired',
            field=models.DateField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('r', 'Racik'), ('g', 'Generic'), ('An', 'Khusus Anak (0-17 tahun)'), ('ot', 'Penyakit Orang Tua'), ('a', 'Alergi'), ('h', 'Herbal/Suplemen'), ('pd', 'Penyakit dalam')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('b', 'Botol/Sirup'), ('s', '1 Strip'), ('c', '1 Butir Kapsul'), ('k', 'Kotak/Kemasan')], default='Kapsul', max_length=100),
        ),
    ]
