# Generated by Django 4.2.5 on 2023-09-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_item_jenis_obat_alter_item_satuan_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('pd', 'Penyakit dalam'), ('ot', 'Penyakit Orang Tua'), ('h', 'Herbal/Suplemen'), ('a', 'Alergi'), ('g', 'Generic'), ('r', 'Racik'), ('An', 'Khusus Anak (0-17 tahun)')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('b', 'Botol/Sirup'), ('k', 'Kotak/Kemasan'), ('c', '1 Butir Kapsul'), ('s', '1 Strip')], default='Kapsul', max_length=100),
        ),
    ]
