# Generated by Django 4.2.5 on 2023-09-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_item_expired_alter_item_jenis_obat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expired',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('pd', 'Penyakit dalam'), ('An', 'Khusus Anak (0-17 tahun)'), ('r', 'Racik'), ('h', 'Herbal/Suplemen'), ('g', 'Generic'), ('a', 'Alergi'), ('ot', 'Penyakit Orang Tua')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('c', '1 Butir Kapsul'), ('k', 'Kotak/Kemasan'), ('s', '1 Strip'), ('b', 'Botol/Sirup')], default='Kapsul', max_length=100),
        ),
    ]
