# Generated by Django 4.2.5 on 2023-09-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_item_jenis_obat_alter_item_satuan_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('r', 'Racik'), ('h', 'Herbal/Suplemen'), ('a', 'Alergi'), ('pd', 'Penyakit dalam'), ('ot', 'Penyakit Orang Tua'), ('An', 'Khusus Anak (0-17 tahun)'), ('g', 'Generic')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('s', '1 Strip'), ('b', 'Botol/Sirup'), ('k', 'Kotak/Kemasan'), ('c', '1 Butir Kapsul')], default='Kapsul', max_length=100),
        ),
    ]
