# Generated by Django 4.2.5 on 2023-09-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_item_jenis_obat_alter_item_satuan_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('a', 'Alergi'), ('r', 'Racik'), ('h', 'Herbal/Suplemen'), ('g', 'Generic'), ('An', 'Khusus Anak (0-17 tahun)'), ('ot', 'Penyakit Orang Tua'), ('pd', 'Penyakit dalam')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('c', '1 Butir Kapsul'), ('k', 'Kotak/Kemasan'), ('b', 'Botol/Sirup'), ('s', '1 Strip')], default='Kapsul', max_length=100),
        ),
    ]
