# Generated by Django 4.2.5 on 2023-09-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_item_jenis_obat_alter_item_satuan_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Generic', 'Generic'), ('Racik', 'Racik'), ('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)'), ('Herbal/Suplemen', 'Herbal/Suplemen'), ('Obat Hati', 'Ibadah'), ('Lansia', 'Penyakit Orang Tua'), ('Alergi', 'Alergi'), ('Penyakit Dalam', 'Penyakit dalam')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('Kapsul', '1 Butir Kapsul'), ('Botol', 'Botol/Sirup'), ('Strip', '1 Strip'), ('Kotak/Kemasan', 'Kotak/Kemasan')], default='Kapsul', max_length=100),
        ),
    ]
