# Generated by Django 4.2.5 on 2023-09-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_item_jenis_obat_alter_item_satuan_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Obat Hati', 'Ibadah'), ('Penyakit Dalam', 'Penyakit dalam'), ('Alergi', 'Alergi'), ('Lansia', 'Penyakit Orang Tua'), ('Herbal/Suplemen', 'Herbal/Suplemen'), ('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)'), ('Generic', 'Generic'), ('Racik', 'Racik')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('Botol', 'Botol/Sirup'), ('Kapsul', '1 Butir Kapsul'), ('Kotak/Kemasan', 'Kotak/Kemasan'), ('Strip', '1 Strip')], default='Kapsul', max_length=100),
        ),
    ]
