# Generated by Django 4.2.5 on 2023-09-19 09:04

import django.contrib.admin.widgets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_item_jenis_obat_alter_item_satuan_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expired',
            field=models.DateField(verbose_name=django.contrib.admin.widgets.AdminDateWidget),
        ),
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Penyakit Dalam', 'Penyakit dalam'), ('Lansia', 'Penyakit Orang Tua'), ('Racik', 'Racik'), ('Herbal/Suplemen', 'Herbal/Suplemen'), ('Alergi', 'Alergi'), ('Generic', 'Generic'), ('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)'), ('Obat Hati', 'Ibadah')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('Kotak/Kemasan', 'Kotak/Kemasan'), ('Strip', '1 Strip'), ('Kapsul', '1 Butir Kapsul'), ('Sachete', 'Sachete'), ('Botol', 'Botol/Sirup')], default='Kapsul', max_length=100),
        ),
    ]
