# Generated by Django 4.2.5 on 2023-09-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_item_jenis_obat_alter_item_satuan_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Generic', 'Generic'), ('Racik', 'Racik'), ('Herbal/Suplemen', 'Herbal/Suplemen'), ('Penyakit Dalam', 'Penyakit dalam'), ('Lansia', 'Penyakit Orang Tua'), ('Ibadah', 'Obat Hati'), ('Alergi', 'Alergi'), ('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('Strip', '1 Strip'), ('Sachete', 'Sachete'), ('Botol', 'Botol/Sirup'), ('Kotak/Kemasan', 'Kotak/Kemasan'), ('Kapsul', '1 Butir Kapsul')], default='Kapsul', max_length=100),
        ),
    ]
