# Generated by Django 4.2.5 on 2023-09-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_item_jenis_obat_alter_item_satuan_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='expired',
            field=models.DateField(verbose_name='Expired (format : yy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Ibadah', 'Obat Hati'), ('Racik', 'Racik'), ('Generic', 'Generic'), ('Alergi', 'Alergi'), ('Penyakit Dalam', 'Penyakit dalam'), ('Herbal/Suplemen', 'Herbal/Suplemen'), ('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)'), ('Lansia', 'Penyakit Orang Tua')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('Strip', '1 Strip'), ('Botol', 'Botol/Sirup'), ('Sachete', 'Sachete'), ('Kotak/Kemasan', 'Kotak/Kemasan'), ('Kapsul', '1 Butir Kapsul')], default='Kapsul', max_length=100),
        ),
    ]
