# Generated by Django 4.2.5 on 2023-09-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_item_amount_alter_item_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Racik', 'Racik'), ('Alergi', 'Alergi'), ('Generic', 'Generic'), ('Ibadah', 'Obat Hati'), ('Herbal/Suplemen', 'Herbal/Suplemen'), ('Lansia', 'Penyakit Orang Tua'), ('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)'), ('Penyakit Dalam', 'Penyakit dalam')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('Botol', 'Botol/Sirup'), ('Strip', '1 Strip'), ('Kapsul', '1 Butir Kapsul'), ('Sachete', 'Sachete'), ('Kotak/Kemasan', 'Kotak/Kemasan')], default='Kapsul', max_length=100),
        ),
    ]
