# Generated by Django 4.2.5 on 2023-09-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_item_jenis_obat_alter_item_satuan_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expired',
            field=models.DateField(verbose_name='Expired \n(format : yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Ibadah', 'Obat Hati'), ('Alergi', 'Alergi'), ('Penyakit Dalam', 'Penyakit dalam'), ('Racik', 'Racik'), ('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)'), ('Generic', 'Generic'), ('Herbal/Suplemen', 'Herbal/Suplemen'), ('Lansia', 'Penyakit Orang Tua')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('Kapsul', '1 Butir Kapsul'), ('Sachete', 'Sachete'), ('Botol', 'Botol/Sirup'), ('Kotak/Kemasan', 'Kotak/Kemasan'), ('Strip', '1 Strip')], default='Kapsul', max_length=100),
        ),
    ]
