# Generated by Django 4.2.5 on 2023-09-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_item_expired_alter_item_jenis_obat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Ibadah', 'Obat Hati'), ('Lansia', 'Penyakit Orang Tua'), ('Penyakit Dalam', 'Penyakit dalam'), ('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)'), ('Generic', 'Generic'), ('Racik', 'Racik'), ('Alergi', 'Alergi'), ('Herbal/Suplemen', 'Herbal/Suplemen')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('Sachete', 'Sachete'), ('Kapsul', '1 Butir Kapsul'), ('Strip', '1 Strip'), ('Botol', 'Botol/Sirup'), ('Kotak/Kemasan', 'Kotak/Kemasan')], default='Kapsul', max_length=100),
        ),
    ]
