# Generated by Django 4.2.5 on 2023-09-25 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0026_alter_item_jenis_obat_alter_item_satuan_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Racik', 'Racik'), ('Penyakit Dalam', 'Penyakit dalam'), ('Lansia', 'Penyakit Orang Tua'), ('Generic', 'Generic'), ('Alergi', 'Alergi'), ('Ibadah', 'Obat Hati'), ('Herbal/Suplemen', 'Herbal/Suplemen'), ('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('Strip', '1 Strip'), ('Sachete', 'Sachete'), ('Kotak/Kemasan', 'Kotak/Kemasan'), ('Kapsul', '1 Butir Kapsul'), ('Botol', 'Botol/Sirup')], default='Kapsul', max_length=100),
        ),
    ]
