# Generated by Django 4.2.5 on 2023-09-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_item_user_alter_item_jenis_obat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)'), ('Alergi', 'Alergi'), ('Racik', 'Racik'), ('Penyakit Dalam', 'Penyakit dalam'), ('Ibadah', 'Obat Hati'), ('Lansia', 'Penyakit Orang Tua'), ('Generic', 'Generic'), ('Herbal/Suplemen', 'Herbal/Suplemen')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('Kotak/Kemasan', 'Kotak/Kemasan'), ('Kapsul', '1 Butir Kapsul'), ('Sachete', 'Sachete'), ('Botol', 'Botol/Sirup'), ('Strip', '1 Strip')], default='Kapsul', max_length=100),
        ),
    ]
