# Generated by Django 4.2.5 on 2023-10-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_item_jenis_obat_alter_item_satuan_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Alergi', 'Alergi'), ('Generic', 'Generic'), ('Ibadah', 'Obat Hati'), ('Racik', 'Racik'), ('Lansia', 'Penyakit Orang Tua'), ('Herbal/Suplemen', 'Herbal/Suplemen'), ('Penyakit Dalam', 'Penyakit dalam'), ('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('Kotak/Kemasan', 'Kotak/Kemasan'), ('Botol', 'Botol/Sirup'), ('Strip', '1 Strip'), ('Sachete', 'Sachete'), ('Kapsul', '1 Butir Kapsul')], default='Kapsul', max_length=100),
        ),
    ]
