# Generated by Django 4.2.5 on 2023-10-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_item_jenis_obat_alter_item_satuan_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Generic', 'Generic'), ('Herbal/Suplemen', 'Herbal/Suplemen'), ('Penyakit Dalam', 'Penyakit dalam'), ('Racik', 'Racik'), ('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)'), ('Alergi', 'Alergi'), ('Ibadah', 'Obat Hati'), ('Lansia', 'Penyakit Orang Tua')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('Kotak/Kemasan', 'Kotak/Kemasan'), ('Kapsul', '1 Butir Kapsul'), ('Sachete', 'Sachete'), ('Strip', '1 Strip'), ('Botol', 'Botol/Sirup')], default='Kapsul', max_length=100),
        ),
    ]
