# Generated by Django 4.2.5 on 2023-10-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_item_jenis_obat_alter_item_satuan_harga'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gambar',
            field=models.FileField(default=1, upload_to=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Racik', 'Racik'), ('Ibadah', 'Obat Hati'), ('Penyakit Dalam', 'Penyakit dalam'), ('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)'), ('Herbal/Suplemen', 'Herbal/Suplemen'), ('Alergi', 'Alergi'), ('Lansia', 'Penyakit Orang Tua'), ('Generic', 'Generic')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('Kotak/Kemasan', 'Kotak/Kemasan'), ('Kapsul', '1 Butir Kapsul'), ('Strip', '1 Strip'), ('Sachete', 'Sachete'), ('Botol', 'Botol/Sirup')], default='Kapsul', max_length=100),
        ),
    ]
