# Generated by Django 4.2.5 on 2023-10-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_item_gambar_alter_item_jenis_obat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Racik', 'Racik'), ('Ibadah', 'Obat Hati'), ('Alergi', 'Alergi'), ('Generic', 'Generic'), ('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)'), ('Herbal/Suplemen', 'Herbal/Suplemen'), ('Penyakit Dalam', 'Penyakit dalam'), ('Lansia', 'Penyakit Orang Tua')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('Sachete', 'Sachete'), ('Botol', 'Botol/Sirup'), ('Kotak/Kemasan', 'Kotak/Kemasan'), ('Kapsul', '1 Butir Kapsul'), ('Strip', '1 Strip')], default='Kapsul', max_length=100),
        ),
    ]
