# Generated by Django 4.2.5 on 2023-10-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_item_gambar_alter_item_jenis_obat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Lansia', 'Penyakit Orang Tua'), ('Generic', 'Generic'), ('Racik', 'Racik'), ('Alergi', 'Alergi'), ('Herbal/Suplemen', 'Herbal/Suplemen'), ('Penyakit Dalam', 'Penyakit dalam'), ('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)'), ('Ibadah', 'Obat Hati')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('Strip', '1 Strip'), ('Kotak/Kemasan', 'Kotak/Kemasan'), ('Sachete', 'Sachete'), ('Botol', 'Botol/Sirup'), ('Kapsul', '1 Butir Kapsul')], default='Kapsul', max_length=100),
        ),
    ]
