# Generated by Django 4.2.5 on 2023-10-04 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0034_alter_item_jenis_obat_alter_item_satuan_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Ibadah', 'Obat Hati'), ('Herbal/Suplemen', 'Herbal/Suplemen'), ('Racik', 'Racik'), ('Lansia', 'Penyakit Orang Tua'), ('Penyakit Dalam', 'Penyakit dalam'), ('Alergi', 'Alergi'), ('Generic', 'Generic'), ('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)')], default='Generic', max_length=100),
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.FileField(upload_to='')),
                ('nama_profile', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
