# Generated by Django 4.2.5 on 2023-10-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_item_jenis_obat_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gambar',
        ),
        migrations.AlterField(
            model_name='item',
            name='jenis_obat',
            field=models.CharField(choices=[('Penyakit Dalam', 'Penyakit dalam'), ('Alergi', 'Alergi'), ('Anak (0-17 tahun)', 'Khusus Anak (0-17 tahun)'), ('Ibadah', 'Obat Hati'), ('Lansia', 'Penyakit Orang Tua'), ('Herbal/Suplemen', 'Herbal/Suplemen'), ('Racik', 'Racik'), ('Generic', 'Generic')], default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='satuan_harga',
            field=models.CharField(choices=[('Kapsul', '1 Butir Kapsul'), ('Kotak/Kemasan', 'Kotak/Kemasan'), ('Sachete', 'Sachete'), ('Botol', 'Botol/Sirup'), ('Strip', '1 Strip')], default='Kapsul', max_length=100),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_picture',
            field=models.ImageField(upload_to=None),
        ),
    ]
